name: CI Test

on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: luthersystems/build-go:v0.0.68
    steps:
    - uses: actions/checkout@v3.5.0
    - name: Run CI
      run: make citest
